name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Golang environment
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.7'
      - name: Install Dependencies
        run: |
          go build

      - name: Run Tests
        run: |
          go run main.go